### ISSUE TITLE
Page range not properly converted

### ISSUE THREAD

**Issue by diogotcorreia** [JonasLoos/bibtex-to-hayagriva-webapp#1]
Hey,
I was citing [10.1145/2484313.2484368](https://dl.acm.org/doi/abs/10.1145/2484313.2484368) and it seems like the BibTex given from the ACM website does not get its page range converted correctly, since only the first page is included.

BibTex:
```bibtex
@inproceedings{10.1145/2484313.2484368,
author = {Vanhoef, Mathy and Piessens, Frank},
title = {Practical verification of WPA-TKIP vulnerabilities},
year = {2013},
isbn = {9781450317672},
publisher = {Association for Computing Machinery},
address = {New York, NY, USA},
url = {https://doi.org/10.1145/2484313.2484368},
doi = {10.1145/2484313.2484368},
abstract = {We describe three attacks on the Wi-Fi Protected Access Temporal Key Integrity Protocol (WPA-TKIP). The first attack is a Denial of Service attack that can be executed by injecting only two frames every minute. The second attack demonstrates how fragmentation of 802.11 frames can be used to inject an arbitrary amount of packets, and we show that this can be used to perform a portscan on any client. The third attack enables an attacker to reset the internal state of the Michael algorithm. We show that this can be used to efficiently decrypt arbitrary packets sent towards a client. We also report on implementation vulnerabilities discovered in some wireless devices. Finally we demonstrate that our attacks can be executed in realistic environments.},
booktitle = {Proceedings of the 8th ACM SIGSAC Symposium on Information, Computer and Communications Security},
pages = {427–436},
numpages = {10},
keywords = {wpa, tkip, fragmentation, driver vulnerabilities, dos, decryption, 802.11},
location = {Hangzhou, China},
series = {ASIA CCS '13}
}
```

Output:
```yaml
10.1145/2484313.2484368:
  type: article
  title: Practical verification of WPA-TKIP vulnerabilities
  author:
  - Vanhoef, Mathy
  - Piessens, Frank
  date: 2013
  page-range: 427 # <--- here's the problem, should be 427-436
  url: https://doi.org/10.1145/2484313.2484368
  serial-number:
    doi: 10.1145/2484313.2484368
    isbn: '9781450317672'
  parent:
    type: proceedings
    title: Proceedings of the 8th ACM SIGSAC Symposium on Information, Computer and Communications Security
    publisher: Association for Computing Machinery
    location: Hangzhou, China
    parent:
      type: proceedings
      title: ASIA CCS '13
```

It might also make sense to map `numpages` to hayagriva's `page-total`.

Thank you for this awesome webapp!
